version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Testcicd
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 1000

